# QuestaSim UVM compile order (relative to repo root)
rtl/pcie_ctrl/rivet_pkg.sv
rtl/pcie_ctrl/dll/rivet_dll_mac_if.sv
rtl/pcie_ctrl/dll/rivet_dll_crc16.sv
rtl/pcie_ctrl/dll/rivet_dll_lcrc32.sv
rtl/pcie_ctrl/dll/rivet_dllp_tx.sv
rtl/pcie_ctrl/dll/rivet_dllp_rx.sv
rtl/pcie_ctrl/dll/rivet_dll_fc.sv
rtl/pcie_ctrl/dll/rivet_dll_sm.sv
rtl/pcie_ctrl/dll/rivet_dll_replay.sv
rtl/pcie_ctrl/dll/rivet_dll_tlp_tx.sv
rtl/pcie_ctrl/dll/rivet_dll_tlp_rx.sv
rtl/pcie_ctrl/dll/rivet_dll_tl_pack.sv
rtl/pcie_ctrl/dll/rivet_dll_tl_unpack.sv
rtl/pcie_ctrl/dll/rivet_dll.sv
rtl/pcie_ctrl/tl/rivet_tl_fc_stub.sv
rtl/pcie_ctrl/mac/rivet_mac_timer.sv
rtl/pcie_ctrl/mac/rivet_ltssm.sv
rtl/pcie_ctrl/mac/rivet_mac_os_tx.sv
rtl/pcie_ctrl/mac/rivet_mac_os_rx.sv
rtl/pcie_ctrl/mac/rivet_mac_scrambler.sv
rtl/pcie_ctrl/mac/rivet_mac_descrambler.sv
rtl/pcie_ctrl/mac/rivet_mac_pipe_adapter.sv
rtl/pcie_ctrl/mac/rivet_mac.sv
rtl/pcie_ctrl/rivet_pcie_ctrl.sv
rtl/interfaces/rivet_pipe_if.sv
rtl/interfaces/rivet_link_status_if.sv
rtl/interfaces/rivet_axi_st_if.sv
rtl/interfaces/rivet_cfg_mgmt_if.sv
rtl/interfaces/rivet_companion_if.sv
tb/uvm/rivet_uvm_pkg.sv
tb/uvm/rivet_tb_top.sv
